## - 학습 3은 학습 2를 기반으로 진행합니다 (중반부터 학습 3 진행)

## tensorflow 모델 생성하기
**출처 ** <br>
- https://www.youtube.com/watch?v=NZz2yq0G5LU
- http://bcho.tistory.com/1154

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from tensorflow.examples.tutorials.mnist import input_data

### input과 label 데이터 설정
** 먼저 간단한 모델을 살펴보자 ** 

In [3]:
input_data = [[1,5,3,7,8,10,12],
              [5,8,10,3,9,7,1]]
label_data = [[0,0,0,1,0],
              [1,0,0,0,0]]

In [4]:
INPUT_SIZE = 7 
HIDDEN_SIZE_1 = 10
HIDDEN_SIZE_2 = 8
CLASSES = 5

** shape 에서 첫 번째 요소는 batch의 크기. 일반적으로 잘 모르기 때문에 None으로 써도 된다. **

In [5]:
x = tf.placeholder(tf.float32, shape = [None, INPUT_SIZE], name="x" )
y = tf.placeholder(tf.float32, shape = [None, CLASSES], name="y" )

In [6]:
tensor_map = {x : input_data, y : label_data}

** input weight 정의 ** 

In [7]:
weight_hidden_1 = tf.Variable( tf.truncated_normal(shape=[INPUT_SIZE, HIDDEN_SIZE_1]) , dtype=tf.float32 ) 

** bias 정의 ** 

In [8]:
bias_hidden_1 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_1]) , dtype=tf.float32 )

In [9]:
tf.matmul( x , weight_hidden_1 )

<tf.Tensor 'MatMul:0' shape=(?, 10) dtype=float32>

In [10]:
print (x)
print (weight_hidden_1)

Tensor("x:0", shape=(?, 7), dtype=float32)
Tensor("Variable/read:0", shape=(7, 10), dtype=float32)


In [11]:
hidden_1 = tf.matmul( x , weight_hidden_1 ) + bias_hidden_1

In [12]:
weight_hidden_2 = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_1, HIDDEN_SIZE_2]) , dtype=tf.float32 ) 
bias_hidden_2 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_2]) , dtype=tf.float32 )

In [13]:
hidden_2 = tf.matmul( hidden_1 , weight_hidden_2 ) + bias_hidden_2

In [14]:
weight_output = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_2, CLASSES]) , dtype=tf.float32 ) 
bias_output = tf.Variable( tf.zeros(shape=[CLASSES]) , dtype=tf.float32 )

In [15]:
answer = tf.matmul( hidden_2 , weight_output ) + bias_output

** 위의 내용을 한 번에 모아서 해보자 ** 

신경망을 미리 설계해 놓고 아래에서 연산을 수행하여 답을 도출해낸다

In [16]:
weight_hidden_1 = tf.Variable( tf.truncated_normal(shape=[INPUT_SIZE, HIDDEN_SIZE_1]) , dtype=tf.float32 ) 
bias_hidden_1 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_1]) , dtype=tf.float32 )

weight_hidden_2 = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_1, HIDDEN_SIZE_2]) , dtype=tf.float32 ) 
bias_hidden_2 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_2]) , dtype=tf.float32 )

weight_output = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_2, CLASSES]) , dtype=tf.float32 ) 
bias_output = tf.Variable( tf.zeros(shape=[CLASSES]) , dtype=tf.float32 )

In [17]:
hidden_1 = tf.matmul( x , weight_hidden_1 ) + bias_hidden_1
hidden_2 = tf.matmul( hidden_1 , weight_hidden_2 ) + bias_hidden_2
answer = tf.matmul( hidden_2 , weight_output ) + bias_output

### 구조
    Input -  ㅁ  - ㅁ  - ㅁ - ㅁ   - ㅁ - ㅁ  - answer
             |     |    |    |     |    |
             w1   b2    w2   b2    wo   bo
             
    
    인풋   히든1  2  결과  

    7     10    8   5

In [18]:
print (x)
print (hidden_1)
print (hidden_2)
print (answer)

Tensor("x:0", shape=(?, 7), dtype=float32)
Tensor("add_3:0", shape=(?, 10), dtype=float32)
Tensor("add_4:0", shape=(?, 8), dtype=float32)
Tensor("add_5:0", shape=(?, 5), dtype=float32)


In [19]:
print (weight_hidden_1)
print (bias_hidden_1)

print (weight_hidden_2)
print (bias_hidden_2)

print (weight_output)
print (bias_output)

Tensor("Variable_6/read:0", shape=(7, 10), dtype=float32)
Tensor("Variable_7/read:0", shape=(10,), dtype=float32)
Tensor("Variable_8/read:0", shape=(10, 8), dtype=float32)
Tensor("Variable_9/read:0", shape=(8,), dtype=float32)
Tensor("Variable_10/read:0", shape=(8, 5), dtype=float32)
Tensor("Variable_11/read:0", shape=(5,), dtype=float32)


** sigmoid  함수 적용 법 ** 

In [20]:
weight_hidden_1 = tf.Variable( tf.truncated_normal(shape=[INPUT_SIZE, HIDDEN_SIZE_1]) , dtype=tf.float32 ) 
bias_hidden_1 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_1]) , dtype=tf.float32 )
hidden_1 = tf.sigmoid(tf.matmul( x , weight_hidden_1 ) + bias_hidden_1)

weight_hidden_2 = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_1, HIDDEN_SIZE_2]) , dtype=tf.float32 ) 
bias_hidden_2 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_2]) , dtype=tf.float32 )
hidden_2 = tf.sigmoid(tf.matmul( hidden_1 , weight_hidden_2 ) + bias_hidden_2)

weight_output = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_2, CLASSES]) , dtype=tf.float32 ) 
bias_output = tf.Variable( tf.zeros(shape=[CLASSES]) , dtype=tf.float32 )

answer = tf.sigmoid(tf.matmul( hidden_2 , weight_output ) + bias_output)

** cost 엔트로피 ** ( tip : 매뉴얼을 항상 자주 보자 )

In [21]:
cost = -y*tf.log(answer)-(1-y)*tf.log((1-answer))

In [22]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
sess.run(cost, feed_dict = tensor_map)

array([[ 0.12725647,  0.94917715,  1.55667984,  0.18586321,  1.14814878],
       [ 3.00087166,  0.76838911,  1.09240842,  1.86383474,  0.65159225]], dtype=float32)

** recude sum 과 reduce mean 사용해보기 **

In [23]:
cost = tf.reduce_sum(-y*tf.log(answer)-(1-y)*tf.log((1-answer)))

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
sess.run(cost, feed_dict = tensor_map)

9.898283

In [24]:
cost = tf.reduce_mean(-y*tf.log(answer)-(1-y)*tf.log((1-answer)))

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
sess.run(cost, feed_dict = tensor_map)

1.6460587

** 수행 ** 
- cost를 최소화 하는 방향으로 최적화 해야 되니까 gradient descent가 필요.
- learning rate 사용



#### 조대협님의 블로그에서 가져온 내용 (Mnist data를 기준으로 한다. 자세한 내용은 링크 참조)

우리가 구하고자 하는 값은 x 값으로 학습을 시켜서 0~9를 가장 잘 구별해내는 W와 b의 값을 찾는 일이다. 

여기서 코드를 주의깊게 봤다면 하나의 의문이 생길것이다.

x의 데이타는 총 55000개로, 55000x784 행렬이 되고, W는 784x10 행렬이다. 이 둘을 곱하면, 55000x10 행렬이 되는데, b는 1x10 행렬로 차원이 달라서 합이 되지 않는다. 

텐서플로우와 파이썬에서는 이렇게 차원이 다른 행렬을 큰 행렬의 크기로 늘려주는 기능이 있는데, 이를 브로드 캐스팅이라고 한다. (브로드 캐스팅 개념 참고 - http://bcho.tistory.com/1153)

브로드 캐스팅에 의해서 b는 55000x10 사이즈로 자동으로 늘어나고 각 행에는 첫행과 같은 데이타들로 채워지게 된다. 

소프트맥스 알고리즘을 이해하고 사용해도 좋지만, 텐서플로우에는 이미 tf.nn.softmax 라는 함수로 만들어져 있고, 대부분 많이 알려진 머신러닝 모델들은 샘플들이 많이 있기 때문에, 대략적인 원리만 이해하고 가져다 쓰는 것을 권장한다.

보통 모델을 다 이해하려고 하다가 수학에서 부딪혀서 포기하는 경우가 많은데, 디테일한 모델을 이해하기 힘들면, 그냥 함수나 예제코드를 가져다 쓰는 방법으로 접근하자. 

우리가 일반적인 프로그래밍에서도 해쉬테이블이나 트리와 같은 자료구조에 대해서 대략적인 개념만 이해하고 미리 정의된 라이브러리를 사용하지 직접 해쉬 테이블등을 구현하는 경우는 드물다.


### 코스트(비용) 함수

이 소프트맥스 함수에 대한 코스트 함수는 크로스엔트로피 (Cross entropy) 함수의 평균을 이용하는데, 복잡한 산식 없이 그냥 외워서 쓰자. 
다행이도 크로스엔트로피 함수역시 함수로 구현이 되어있다.

** Cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(tf.matmul(x, W) + b, y_)) ** 

가설에 의해 계산된 값 y를 넣지 않고 tf.matmul(x, W) + b 를 넣은 이유는  tf.nn.softmax_cross_entropy_with_logits 함수 자체가 softmax를 포함하기 때문이다. y_은 학습을 위해서 입력된 값이다.  


-> 코스트 함수로 위 함수는 써 본 적은 없고, 자세한 내용은 저도 잘 모르겠으나 일단 사용해보겠습니다. 

In [25]:
Learning_Rate = 0.05

cost = tf.reduce_mean(-y*tf.log(answer)-(1-y)*tf.log((1-answer)))
train = tf.train.GradientDescentOptimizer(Learning_Rate).minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(10):
    print (sess.run([train, cost], feed_dict = tensor_map))
    print ("Step : ",i )

[None, 0.93857777]
Step :  0
[None, 0.92473018]
Step :  1
[None, 0.91232836]
Step :  2
[None, 0.90098572]
Step :  3
[None, 0.8904134]
Step :  4
[None, 0.88041723]
Step :  5
[None, 0.8708688]
Step :  6
[None, 0.86168253]
Step :  7
[None, 0.85279971]
Step :  8
[None, 0.84417838]
Step :  9


** 학습 100 번 수행 ** 

In [26]:
for i in range(100):
    print (sess.run([train, cost], feed_dict = tensor_map))
    print ("Step : ",i )

[None, 0.83578843]
Step :  0
[None, 0.82760656]
Step :  1
[None, 0.81961554]
Step :  2
[None, 0.81180131]
Step :  3
[None, 0.80415261]
Step :  4
[None, 0.7966603]
Step :  5
[None, 0.78931677]
Step :  6
[None, 0.78211546]
Step :  7
[None, 0.77505082]
Step :  8
[None, 0.76811802]
Step :  9
[None, 0.76131272]
Step :  10
[None, 0.75463122]
Step :  11
[None, 0.74806988]
Step :  12
[None, 0.74162591]
Step :  13
[None, 0.73529625]
Step :  14
[None, 0.72907853]
Step :  15
[None, 0.72297019]
Step :  16
[None, 0.71696913]
Step :  17
[None, 0.71107304]
Step :  18
[None, 0.70528018]
Step :  19
[None, 0.69958848]
Step :  20
[None, 0.69399625]
Step :  21
[None, 0.68850154]
Step :  22
[None, 0.68310297]
Step :  23
[None, 0.67779869]
Step :  24
[None, 0.67258716]
Step :  25
[None, 0.66746688]
Step :  26
[None, 0.66243613]
Step :  27
[None, 0.65749365]
Step :  28
[None, 0.65263784]
Step :  29
[None, 0.6478672]
Step :  30
[None, 0.64318025]
Step :  31
[None, 0.63857567]
Step :  32
[None, 0.63405198]
Ste

In [27]:
sess.close()

 <br><br>

## 학습 3 시작 

### cost 에서 reduce_mean 을 제거하고 수행해보자

** reduce_mean은 모든 차원의 값을 제거하고 나서 하나의 값으로 나타낸다 ** 

    1 2 3 4
    5 6 7 8 

reduce_mean은 위와 같은 배열이 있으면 (1+2+3+4+5+6+7+8)/8 연산을 통해서 모든 차원을 제거하고 하나의 값만 출력해준다. 

In [28]:
Learning_Rate = 0.05

cost = -y*tf.log(answer)-(1-y)*tf.log((1-answer))
train = tf.train.GradientDescentOptimizer(Learning_Rate).minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

loss = sess.run(cost, feed_dict = tensor_map)
print (loss) 
print ()    

for i in range(10):
    loss = sess.run(cost, feed_dict = tensor_map)
    print (loss)

sess.close()

[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.96921289  0.61158365]]

[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.96921289  0.61158365]]
[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.96921289  0.61158365]]
[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.96921289  0.61158365]]
[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.96921289  0.61158365]]
[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.96921289  0.61158365]]
[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.96921289  0.61158365]]
[[ 1.0048455   0.84496111  2.10641766  0.17243485  0.44292724]
 [ 0.53914297  1.00608134  1.41389239  1.969212

**   https://www.tensorflow.org/api_docs/python/tf/reduce_mean 에서 확인해보세요  ** 

** 예시 (For example): ** 

** 비교하기 쉽게 출력 해보자 ** 

- 차원의 차이가 아래와 같이 난다. 

In [29]:
Learning_Rate = 0.05

cost_ = -y*tf.log(answer)-(1-y)*tf.log((1-answer))
cost = tf.reduce_sum(cost_, reduction_indices=1)
train = tf.train.GradientDescentOptimizer(Learning_Rate).minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init) 

loss_, loss = sess.run([cost_, cost], feed_dict = tensor_map)
print (loss_)
print (loss)
    
sess.close()

[[ 0.26175556  0.58373004  0.60565728  0.30459416  0.06072804]
 [ 0.99035496  0.47694016  1.10001564  2.00055599  0.01510703]]
[ 1.81646514  4.58297396]



- 배열에서 원소 하나 하나는 함수와 가지는 loss를 의미한다

- 따라서, 함수 하나와 모든 점들간의 loss를 보기 위해서 모든 파라미터에 대하여 평균을 구하거나 합을 구하는 reduce를 사용

### 위에서 reduce_sum 을 구했으니까, reduce_mean이 필요

- reduce_mean을 해주면 차원이 또 줄어든다 

In [30]:
Learning_Rate = 0.05

cost_ = -y*tf.log(answer)-(1-y)*tf.log((1-answer))
cost = tf.reduce_sum(cost_, reduction_indices=1)
cost = tf.reduce_mean(cost, reduction_indices=0)
train = tf.train.GradientDescentOptimizer(Learning_Rate).minimize(cost)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init) 

for i in range(1000):
    if i%100 == 0:
        _ , loss = sess.run([train, cost], feed_dict = tensor_map)
        print (i)
        print (loss)
    
sess.close()

0
3.04245
100
2.89862
200
2.76912
300
2.65249
400
2.54735
500
2.45231
600
2.3659
700
2.28701
800
2.21607
900
2.15454


### accuracy를 구해보자!! 

In [31]:
Learning_Rate = 0.05

cost_ = -y*tf.log(answer)-(1-y)*tf.log((1-answer))
cost = tf.reduce_sum(cost_, reduction_indices=1)
cost = tf.reduce_mean(cost, reduction_indices=0)
train = tf.train.GradientDescentOptimizer(Learning_Rate).minimize(cost)

** train 해서 나온 answer 중에서 가장 큰 것과, label 과 비교한다. ** 

In [32]:
comp_pred = tf.equal( tf.arg_max(answer, 1), tf.arg_max(y, 1) )
accuracy = tf.reduce_mean(tf.cast(comp_pred, tf.float32))

In [33]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init) 

for i in range(1000):
    _ , loss, acc = sess.run([train, cost, accuracy], feed_dict = tensor_map)
    if i%100 == 0: 
        print (i)
        print (loss)
        print (acc)
        print ()
    
sess.close()

0
4.98481
0.5

100
1.39882
1.0

200
1.07151
1.0

300
0.745282
1.0

400
0.510762
1.0

500
0.371681
1.0

600
0.285704
1.0

700
0.229145
1.0

800
0.18983
1.0

900
0.161219
1.0



### 텐서플로우는 체크포인트에 weight 정보를 넣는다. test 모델에서 파일에 있는 weight를 가져온다. 
- weight 의 아래 쪽에 saver를 만든다

In [34]:
weight_hidden_1 = tf.Variable( tf.truncated_normal(shape=[INPUT_SIZE, HIDDEN_SIZE_1]) , dtype=tf.float32, name="weight_hidden_1" ) 
bias_hidden_1 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_1]) , dtype=tf.float32, name = "bias_hidden_1" )

weight_hidden_2 = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_1, HIDDEN_SIZE_2]) , dtype=tf.float32, name="weight_hidden_2" ) 
bias_hidden_2 = tf.Variable( tf.zeros(shape=[HIDDEN_SIZE_2]) , dtype=tf.float32, name = "bias_hidden_2" )

weight_output = tf.Variable( tf.truncated_normal(shape=[HIDDEN_SIZE_2, CLASSES]) , dtype=tf.float32, name="weight_output" ) 
bias_output = tf.Variable( tf.zeros(shape=[CLASSES]) , dtype=tf.float32, name = "bias_output" )

** 아래의 영역을 추가해준다 ** 

In [35]:
param_list = [weight_hidden_1, bias_hidden_1, weight_hidden_2, bias_hidden_2, weight_output, bias_output ]
saver = tf.train.Saver(param_list)

In [36]:
hidden_1 = tf.matmul( x , weight_hidden_1 , name="hidden_1" ) + bias_hidden_1
hidden_2 = tf.matmul( hidden_1 , weight_hidden_2, name="hidden_2" ) + bias_hidden_2
answer = tf.matmul( hidden_2 , weight_output, name="answer" ) + bias_output

** saver.save 함수를 통하여 파일이 생성됨  ** 

In [37]:
Learning_Rate = 0.05

cost_ = -y*tf.log(answer)-(1-y)*tf.log((1-answer))
cost = tf.reduce_sum(cost_, reduction_indices=1)
cost = tf.reduce_mean(cost, reduction_indices=0)
train = tf.train.GradientDescentOptimizer(Learning_Rate).minimize(cost)

comp_pred = tf.equal( tf.arg_max(answer, 1), tf.arg_max(y, 1) )
accuracy = tf.reduce_mean(tf.cast(comp_pred, tf.float32))

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init) 

for i in range(1000):
    _ , loss, acc = sess.run([train, cost, accuracy], feed_dict = tensor_map)
    if i%100 == 0:
        saver.save(sess, './tensorflow_live.ckpt')
        print (i)
        print (loss)
        print (acc)
    
sess.close()

0
nan
0.0
100
nan
0.0
200
nan
0.0
300
nan
0.0
400
nan
0.0
500
nan
0.0
600
nan
0.0
700
nan
0.0
800
nan
0.0
900
nan
0.0
